### PR TITLE
feat(network-explorer): Introduce graphql client in explorer

### PR DESCRIPTION
**Pull request by akim-bow**

### CODE REVIEW

**Review by folex — CHANGES_REQUESTED** [review]
Could you please describe motivation and consequences of this?

for example, how would we support two copies of code

**Comment by akim-bow** [comment]
> Could you please describe motivation

Motivation - to make frontend aligned with graphql protocol, when producer doesn't change it's API (or doing it very rarely) when Frontend view is changed. Frontend acts as a client or consumer, and according to the GrapgQL protocol, it owns the queries. This change will allows us to make any Frontend changes faster (no need to update deal-ts-client on each data change bcs queries(i.e. data requests) stored in Frontend. I believe it will facilitate our development process and reduce the load from CHAIN team. 

>  and consequences of this? for example, how would we support two copies of code

It's move, not copy. We won't support 2 copies of code. No other negative consequences.

**Comment by AlcibiadesCleinias** [comment]
> It's move, not copy. We won't support 2 copies of code. No other negative consequences.

it seemed that will will support copy of utils module anyway

**Review by AlcibiadesCleinias — CHANGES_REQUESTED** [review]
move dealXplorerClient to additional layer pls, like so:

src/clients/dealExplorerClient/here all sources of the client

**Comment by akim-bow** [comment]
> it seemed that will will support copy of utils module anyway
@AlcibiadesCleinias  hmmm, noo. I will export all dublicated code from ts-client.

**Comment by AlcibiadesCleinias** [comment]
> > move dealXplorerClient to additional layer pls, like so:
> > src/clients/dealExplorerClient/here are all sources of the client {dealExplorerClient.ts, utils, etc...}
> 
> Let's keep it as it is. Otherwise nesting level would be too deep. If we add additional client, we can do this, but it's very unlikely.

Okey, I believe it is necessary, sorry, do not worry, I will add it myself

**Review by AlcibiadesCleinias — APPROVED** [review]
sgtm

**Pull request merged**
